### PR TITLE
Class Search & Review Page Initialization

### PR DESCRIPTION
**Pull request by ryanschwartz88**

### CODE REVIEW

**Comment by xyntechx** [comment]
oop looks like there's a build error :p

**Comment by ryanschwartz88** [comment]
That's my bad. I also did not look at your modifications to the class card closely enough. I was thinking that the whole class card should be clickable instead of having a link component. Should I get rid of the onClick prop or just keep both and figure out conditional hovering state for the card?

**Comment by xyntechx** [comment]
We could have the whole component be clickable :)

**Review by xyntechx — CHANGES_REQUESTED** [review]
### src/components/popup.tsx
Instead of setting the overflow properties using `document.body.style.overflow`, maybe you'd want to use https://github.com/lukeed/clsx?tab=readme-ov-file#tailwind-support instead?

### src/components/class-review/class-card.tsx
Similar comment as above; use clsx instead of manually setting a string conditionally.

### General
Remove `console.log` calls :))

**Comment by ryanschwartz88** [comment]
I was able to use `clsx` for the `ClassCard` component, but I'm a little confused on how I can make the document body clipped with `overflow-hidden` using `clsx`. What did you have in mind?

**Comment by xyntechx** [comment]
I guess it would be difficult since you're setting the style for <body>. Don't worry about it then!

**Review by xyntechx — APPROVED** [review]
LGTM!

**Pull request merged**
