### PR TITLE
Initial implementation of reviews/submit

### PR DESCRIPTION
**Pull request by ryanschwartz88**
## Completed:
- Added `react-star` component dependency.
- Implemented basic frontend design.

## To-Do:
- **Fix Session Problem**: Currently, the user returns false with no timeout. Temp fix is to delay check for user session
- **Consolidate Data for Supabase**: Need to organize data more effectively for integration with Supabase.
- **Develop Dropdown Functions**: Create functions to pull and update header selection dropdowns from Supabase.
- **Implement `handleSubmit()`**: This function is yet to be created and integrated.
- **Form Submission Handling**: Establish which information is required or optional for submission.
- **Future Feature**: Auto-populate class selection if navigating from the review page.

### CODE REVIEW

**Review by xyntechx — CHANGES_REQUESTED** [review]
Thanks Ryan! Here's some notes:

1. Move all the options constants in `src/app/reviews/submit/page.tsx` to a `lib/options.ts` to keep the code clean. You can then export these constants in the `.ts` file and import them in the `tsx` file.
2. Can I check why you implemented `checkSessionTimeout`? If you want to ensure that an authenticated user is accessing the page, you can instead just redirect the user back to home `if (!user)` in the useEffect. As an aside, in the future, we can redirect the user to /reviews (since users can view reviews without being logged in) with a feedback alert saying "You must be logged in to submit reviews".
3. What's the blocker for `handleSubmit`?
4. Any blockers to get data from Supabase?
5. You can use Prettier to format your code. Install the Prettier extension for VSCode and change the tab width in the Prettier settings to 4 :)

We'll merge the PR once these notes are addressed! Thanks!!

**Comment by xyntechx** [comment]
Also, feel free to create tasks in our Notion page with any future TODOs!

**Comment by ryanschwartz88** [comment]
Hi Nyx, 

I'll work on that right now. I used `checkSessionTimeout` because I found that the user was undefined even after logging in when it runs the `if (!user)` conditional. This made me think that the session hasn't been retrieved by the time this conditional runs. The `checkSessionTimeout` was just a temporary fix to allow the user data to be retrieved. How do you think I should approach this? I saw something in Next.js docs about [middleware.ts](https://nextjs.org/docs/app/building-your-application/routing/middleware) that can deal with page authorization. I could also try finding a different work around.

**Comment by xyntechx** [comment]
I think middleware.ts would work. I implemented something similar in https://github.com/xyntechx/asuc-elections. Maybe this would work.

**Comment by xyntechx** [comment]
Although @ryanschwartz88 when I was running your code, the user did eventually have a logged in state even without your timeout function since the useEffect runs every time `user` changes. I'm sure you've realized it too. Setting a timeout isn't the solution though, since we have to hardcode the delay which isn't foolproof.

I think instead of triggering a redirect, we should just disable the inputs and submit button if the user is not authenticated. Keep in mind that we'll only show the button to go to /reviews/submit in /reviews iff the user is authenticated.

So, I suggest removing your timeout function and just check for the session's existence like what I did in account.tsx. Lmk if this sounds good!

**Pull request merged**
